language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - android-24
    - build-tools-24.0.0
    - extra-android-m2repository
    - extra-google-m2repository

script:
  - mvn --settings maven.settings.xml license:check checkstyle:check && ./gradlew clean assembleDebug

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.m2

sudo:
  false
